### PR TITLE
Fix: Restructure collabocate model structure to favour better validation & data storage

### LINKED ISSUE #147: Restructure collabocate model structure to favour better validation & data storage
#### Issue description

In the API server, with the current structure of the collabocate instance model, adding validation might be problematic. it also as an effect on its storage in the database. 
Current structure:
```
  global: boolean;
  instance_name: string;
  github: {
    user_name: string;
    repo_name: string;
  };
  user: UserDocument;
```
but what we want is to destructure/separate the github property to this New structure:
```
  global: boolean;
  instance_name: string;
  github_username: string;
  github_reponame: string;
  user: UserDocument;
```

#

#### Expected behaviour

The collabocate instance model structure should be changed to the new structure as described in the Issue description
 
#

#### Additional context

Repo URL: https://github.com/collabo-community/api-server

#

#### Testing checklist

Note (to contributor taking on this task assignment): Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The collabocate instance model structure has been changed to the new structure as described in the Issue description
- [ ] Other backend functionality still works as before.
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by samuko-things**
#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#147

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] The collabocate instance model structure has been changed to the new structure as described in the Issue description
- [x] Other backend functionality still works as before.
- [x] I certify that I ran my checklist

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

### CODE REVIEW

**Comment by samuko-things** [comment]
@Ifycode, Here's the PR, do check it out

File: @server/@api-user/user.controller.ts [hunk 1]
```diff
@@ -35,10 +35,8 @@ export const getAllUsersController = async (req: Request, res: Response, next: N
                 _id: instance._id,
                 global: instance.global,
                 instance_name: instance.instance_name,
-                github: {
-                  user_name: instance.github.user_name,
-                  repo_name: instance.github.repo_name
-                },
+                github_username: instance.github_username,
+                github_reponame: instance.github_reponame,
```
Comment (Ifycode) [inline @server/@api-user/user.controller.ts]: I left you a message/question on Discord @samuko-things

**Review by Ifycode — CHANGES_REQUESTED** [review]

**Review by Ifycode — APPROVED** [review]
